---
# This file is used by developers who use ./scripts/deploy.sh to set up a local
# development environment to help with development this module.
version: '2'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile8
    volumes:
      - "sitesdefault:/var/www/html/sites/default"
      - ".:/var/www/html/modules/custom/realistic_dummy_content"
    ports:
      - "80"
    links:
      - mysql:mysql
    working_dir: /var/www/html

  drupal8drush8:
    build:
      context: .
      dockerfile: Dockerfile8drush8
    volumes:
      - "sitesdefault:/var/www/html/sites/default"
      - ".:/var/www/html/modules/custom/realistic_dummy_content"
    ports:
      - "80"
    links:
      - mysql:mysql
    working_dir: /var/www/html

  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'

volumes:
  sitesdefault:

# Specifying the network name makes it predictable on all environments,
# for example when we run browser tests.
# See https://github.com/docker/compose/issues/3736.
networks:
  default:
    external:
      name: realistic_dummy_content_default
