# See https://github.com/alberto56/docker-drupal
FROM alberto56/docker-drupal:7.x-dev-2.0

RUN cd ./srv/drupal/www && /usr/bin/drush dl devel -y
RUN echo ''
RUN echo 'To log into this environment, please call ./scripts/uli.sh'
RUN echo ''
