FROM debian

# we'll do all our work in the /testable folder
RUN mkdir /testable

# install curl and php5
RUN apt-get update && apt-get -y install php5 php5-cli php5-curl php5-dev php5-gd php5-mcrypt php5-mysql php-pear

# get composer which will be required to get phpunit
RUN cd /testable && curl -sS https://getcomposer.org/installer | php

# scripts/phpunit-docker-resources/README.txt
COPY scripts/phpunit-docker-resources/composer.json /testable/composer.json

# installing git it required (sometimes?) by composer
RUN apt-get install -y git

# run composer to install phpunit
RUN cd /testable && ./composer.phar update

# install xdebug to get code coverage
RUN git clone git://github.com/derickr/xdebug.git
RUN cd xdebug*; \
  phpize;\
  ./configure --enable-xdebug;\
  make;\
  make install

COPY scripts/phpunit-docker-resources/enable-xdebug.txt /tmp/enable-xdebug.txt
RUN cat /tmp/enable-xdebug.txt >> /etc/php5/cli/php.ini

# scripts/phpunit-docker-resources/README.txt
COPY scripts/phpunit-docker-resources/phpunit.xml /testable/phpunit.xml

ADD api/src /testable/Drupal/realistic_dummy_content_api

RUN cd /testable && ls -lah && ls -lah Drupal/realistic_dummy_content_api && ./vendor/bin/phpunit -v
