<?php
/**
 * @file
 *
 * This module replaces the body field of all node types with custom dummy
 * content; it also replaces the image field of articles and the picture field
 * of users. It does this by placing the dummy replacement content in a
 * specific directory hierarchy, enclosed.
 *
 * This file is left empty because modules do not need to implement any hooks,
 * although hooks are available for finer control over what constitutes
 * dummy content.
 *
 * See realistic_dummy_content.api.php for hooks you can implement.
 * See also the realistic_dummy_content_api module which implements its own
 * hooks.
 *
 * See also https://drupal.org/node/2266627.
 */
