<?php

/**
 * @file
 *
 * Define RealisticDummyContentAPIBase autoload class.
 */

/**
 * The most generic content manipulator.
 *
 * Because Realistic Dummy Content defines content as any data
 * including but not limited to entities, entities are managed
 * by a subclass of this, but we leave the door open to manipulators
 * of other types of data (including menus, for example, which are
 * not entites), which are not yet supported but which could be
 * in future releases.
 */
abstract class RealisticDummyContentAPIBase {
}
