<?php

/**
 * @file
 *
 * Install, deployment (update), and uninstall hooks for this module.
 */

/**
 * Implements hook_uninstall().
 */
function realistic_dummy_content_api_uninstall() {
  // This is an internal variable used by tests to avoid using random
  // images. This is necessary in order to test that the image replacement
  // happens correctly.
  variable_del('realistic_dummy_content_api_rand');
}
